# network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}
network:
  version: 2
  renderer: networkd
  ethernets:
    eth0:
      dhcp4: yes
      dhcp6: yes
      optional: true
  wifis:
    wlan0:
      dhcp4: no
      addresses: [192.168.31.4/24]
      gateway4: 192.168.31.1
      nameservers:
        addresses: [192.168.31.5] 
      access-points:
       # Netgear:
        #  password: 14736ef672abb32b563546bf8709fff09090
        ParadiseCity:
          password: DizzyReed