version: "3"

services:
  roscore:
    image: ros:noetic-ros-core
    command: stdbuf -o L roscore
    tty: true
    stdin_open: true
    environment:
      ROS_IP: ${MASTER_IP}
    # ports:
    #   - 11311:11311
    network_mode: host

  detect:
    build:
      context: ./docker
      dockerfile: Dockerfile
    command: /watchdog.sh detect.py
    tty: true
    stdin_open: true
    environment:
      ROS_MASTER_URI: http://${MASTER_IP}:11311
      ROS_IP: ${MASTER_IP}
    volumes:
      - ./detect:/app
    network_mode: host
    depends_on:
      - roscore

  # detect-v4:
  #   build:
  #     context: ./docker
  #     dockerfile: Dockerfile
  #   command: /watchdog.sh yolo-v4-node.py
  #   tty: true
  #   stdin_open: true
  #   environment:
  #     ROS_MASTER_URI: http://${MASTER_IP}:11311
  #     ROS_IP: ${MASTER_IP}
  #   volumes:
  #     - ./detect/yolo_node:/app
  #   network_mode: host
  #   depends_on:
  #     - roscore

  nav:
    build:
      context: ./docker
      dockerfile: Dockerfile
    command: /watchdog.sh navigation.py
    tty: true
    stdin_open: true
    environment:
      ROS_MASTER_URI: http://${MASTER_IP}:11311
      ROS_IP: ${MASTER_IP}
    volumes:
      - ./navigation:/app
    network_mode: host
    depends_on:
      - roscore
