version: "3"

services:
  roscore:
    image: ros:noetic-ros-core
    command: stdbuf -o L roscore
    tty: true
    stdin_open: true
    ports:
      - 11311:11311
    restart: always

  detect:
    build:
      context: ./docker
      dockerfile: Dockerfile
    command: /watchdog.sh detect.py
    tty: true
    stdin_open: true
    environment:
      ROS_MASTER_URI: http://roscore:11311
    volumes:
      - ./detect:/app
    depends_on:
      - roscore

  nav:
    build:
      context: ./docker
      dockerfile: Dockerfile
    command: /watchdog.sh navigation.py
    tty: true
    stdin_open: true
    environment:
      ROS_MASTER_URI: http://roscore:11311
    volumes:
      - ./navigation:/app
    depends_on:
      - roscore
